POST http://localhost:{{port}}/ingress
Content-Type: text/plain

{"jaeger":"16686:16686"}

###

POST http://localhost:{{port}}/trigger
Content-Type: text/plain

{"name":"runTest"}

###

POST http://localhost:{{port}}/restart
Content-Type: text/plain

["mysql"]

###

POST http://localhost:{{port}}/switch
Content-Type: text/plain

{"nginx":"data2"}

###

POST http://localhost:{{port}}/shutdown

###

POST http://localhost:{{port}}/stop

###

GET http://localhost:{{port}}/info

###

POST http://localhost:{{port}}/start

###

