# curl --location --request POST 'http://localhost:51783/restart'
#--header 'Content-Type: text/plain'
#--data-raw '["mysql"]'
POST http://localhost:{{port}}/restart
Content-Type: text/plain

["mysql"]

###

# curl --location --request POST 'http://localhost:51783/ingress'
#--header 'Content-Type: text/plain'
#--data-raw '{"nginx":"80:39000"}'
POST http://localhost:{{port}}/ingress
Content-Type: text/plain

{"jaeger":"16686:16686"}

###

# curl --location --request POST 'http://localhost:51783/switch'
#--header 'Content-Type: text/plain'
#--data-raw '{"nginx":"data2"}'
POST http://localhost:{{port}}/switch
Content-Type: text/plain

{"nginx":"data2"}

###

# curl --location --request POST 'http://localhost:51783/shutdown'
POST http://localhost:{{port}}/shutdown

###

# curl --location --request POST 'http://localhost:51783/stop'
POST http://localhost:{{port}}/stop

###

# curl --location --request GET 'http://localhost:51783/info'
GET http://localhost:{{port}}/info

###

# curl --location --request POST 'http://localhost:51783/start'
POST http://localhost:{{port}}/start

###

