POST http://localhost:{{port}}/ingress
Content-Type: text/plain

{"nginx":"80:8080"}

###

POST http://localhost:{{port}}/taskGroup
Content-Type: text/plain

{"name":"runTest"}

###

POST http://localhost:{{port}}/restart
Content-Type: text/plain

["jaeger"]

###

POST http://localhost:{{port}}/switch
Content-Type: text/plain

{"name":"group2"}

###

POST http://localhost:{{port}}/shutdown

###

POST http://localhost:{{port}}/stop

###

GET http://localhost:{{port}}/info

###

POST http://localhost:{{port}}/start

###

