version: 1
volumes:
  - name: tmp
    emptyDir: {}
  - name: wlp-output
    emptyDir: {}
  - name: nginx
    switchData:
      normal: ./switch_data_1
      data2: ./switch_data_2
pods:
  - name: nginx
    containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
          - name: nginx
            mountPath: "/home"
  - name: ratings
    containers:
      - name: ratings
        image: docker.io/istio/examples-bookinfo-ratings-v1:1.17.0
  - name: reviews
    depends:
      - ratings
    containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v2:1.17.0
        env:
          LOG_DIR: "/tmp/logs"
        volumeMounts:
          - name: wlp-output
            mountPath: "/opt/ibm/wlp/output"
  - name: productpage
    depends:
      - reviews
    containers:
      - name: productpage
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.17.0
        volumeMounts:
          - name: tmp
            mountPath: "/tmp"