version: 1
volumes:
  - name: nginx
    switchData:
      default: ./switch_data_1
      data2: ./switch_data_2
before:
after:
pods:
  - name: nginx
    containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
          - name: nginx
            mountPath: "/usr/share/nginx/html"
        waitingFor:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1000
  - name: wordpress
    depends:
      - mysql
    containers:
      - name: wordpress
        image: wordpress:latest
        env:
          WORDPRESS_DB_HOST: mysql:3306
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: wordpress
  - name: mysql
    containers:
      - name: mysql
        image: mysql:8.0
        waitingFor:
          tcpSocket:
            port: 3306
          periodSeconds: 1000
        env:
          MYSQL_ROOT_PASSWORD: somewordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress