version: 1
volumes:
  - name: collector
    emptyDir: {}
  - name: test
    emptyDir: {}
trigger:
  runTest:
    - name: do-curl1
      image: alpine/curl
      command:
        - curl
        - "demo/inbound"
    - name: do-curl2
      image: alpine/curl
      command:
        - curl
        - "demo/inbound"
    - name: do-import-jaeger
      image: alpine/curl
      command:
        - curl
        - --request
        - POST
        - "collector/import"
    - name: do-copy-gen
      image: ubuntu
      volumeMounts:
        - name: collector
          mountPath: /home
      bindMounts:
        - hostPath: ./docs
          mountPath: /docs
      command:
        - cp
        - -r
        - /home
        - /docs
pods:
  - name: collector
    containers:
      - name: collector
        image: mockest/collector
        volumeMounts:
          - name: collector
            mountPath: "/home"
        env:
          JAEGER_HOST: jaeger
  - name: jaeger
    containers:
      - name: jaeger-all
        image: jaegertracing/all-in-one:1.42
  - name: demo
    initContainers:
      - name: proxy-init
        image: mockest/proxy
        command:
          - init
        user: 0
        cap:
          add:
            - NET_ADMIN
            - NET_RAW
    containers:
      - name: app
        image: mockest/demo
      - name: proxy
        image: mockest/proxy
        command:
          - proxy
  - name: outbound-demo
    initContainers:
      - name: proxy-init
        image: mockest/proxy
        command:
          - init
        user: 0
        cap:
          add:
            - NET_ADMIN
            - NET_RAW
    containers:
      - name: app
        image: mockest/demo
      - name: proxy
        image: mockest/proxy
        command:
          - proxy