version: 1
volumes:
  - name: collector
  - name: test
taskGroups:
  - name: testrunner
    event: compose_event_start_success
    tasks:
    - name: do-curl1
      image: alpine/curl
      command:
        - curl
        - "demo/inbound"
    - name: do-curl2
      image: alpine/curl
      command:
        - curl
        - "demo/inbound"
  - name: collect
    event: compose_event_task_group_success:testrunner
    tasks:
    - name: do-import-jaeger
      image: alpine/curl
      command:
        - curl
        - --request
        - POST
        - "collector/import"
  - name: gen-mock
    event: compose_event_task_group_success:collect
    tasks:
    - name: do-create-mock
      image: testmesh/mockserver
      volumeMounts:
        - name: collector
          mountPath: /home
      command:
        - stubby
        - -i
        - /home/dump.json
        - -o
        - /home
  - name: copy
    event: compose_event_task_group_success:gen-mock
    tasks:
    - name: do-copy
      image: ubuntu
      volumeMounts:
        - name: collector
          mountPath: /home
      bindMounts:
        - hostPath: ./docs
          mountPath: /docs
      command:
        - cp
        - -r
        - /home
        - /docs
pods:
  - name: collector
    containers:
      - name: collector
        image: testmesh/collector
        volumeMounts:
          - name: collector
            mountPath: "/home"
        env:
          JAEGER_HOST: jaeger
  - name: jaeger
    containers:
      - name: jaeger-all
        image: jaegertracing/all-in-one:1.42
  - name: demo
    initContainers:
      - name: proxy-init
        image: testmesh/proxy
        command:
          - init
        user: 0
        cap:
          add:
            - NET_ADMIN
            - NET_RAW
    containers:
      - name: app
        image: testmesh/demo
      - name: proxy
        image: testmesh/proxy
        command:
          - proxy
  - name: outbound-demo
    initContainers:
      - name: proxy-init
        image: testmesh/proxy
        command:
          - init
        user: 0
        cap:
          add:
            - NET_ADMIN
            - NET_RAW
    containers:
      - name: app
        image: testmesh/demo
      - name: proxy
        image: testmesh/proxy
        command:
          - proxy