version: 1
volumes:
  - name: collector
    emptyDir: {}
  - name: test
    emptyDir: {}
before:
  - name: test
    image: ubuntu
    volumeMounts:
      - name: test
        mountPath: /home
    workingDir: /home
    command:
      - touch
      - before.log
after:
  - name: do-curl
    image: alpine/curl
    command:
      - curl
      - "demo/inbound"
  - name: do-gen
    image: alpine/curl
    command:
      - curl
      - "collector/gen"
  - name: do-copy-before
    image: ubuntu
    volumeMounts:
      - name: test
        mountPath: /home
    bindMounts:
      - hostPath: ./docs
        mountPath: /docs
    command:
      - cp
      - -r
      - /home
      - /docs
  - name: do-copy-gen
    image: ubuntu
    volumeMounts:
      - name: collector
        mountPath: /home
    bindMounts:
      - hostPath: ./docs
        mountPath: /docs
    command:
      - cp
      - -r
      - /home
      - /docs
  - name: do-shutdown
    image: alpine/curl
    command:
      - curl
      - --request
      - POST
      - "agent/shutdown"
pods:
  - name: collector
    containers:
      - name: collector
        image: mockest/collector
        volumeMounts:
          - name: collector
            mountPath: "/home"
  - name: demo
    initContainers:
      - name: proxy-init
        image: mockest/proxy
        command:
          - init
        user: 0
        cap:
          add:
            - NET_ADMIN
            - NET_RAW
    containers:
      - name: app
        image: mockest/demo
      - name: proxy
        image: mockest/proxy
        command:
          - proxy
  - name: outbound-demo
    initContainers:
      - name: proxy-init
        image: mockest/proxy
        command:
          - init
        user: 0
        cap:
          add:
            - NET_ADMIN
            - NET_RAW
    containers:
      - name: app
        image: mockest/demo
      - name: proxy
        image: mockest/proxy
        command:
          - proxy